# This is a basic workflow to help you get started with Actions

name: GitHub workflow for python components

# Controls when the workflow will run
on:
  push:
     branches: [feature/python-comp]
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "init"
  code-checkout:
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout on code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

  build:
    needs: code-checkout
    runs-on: self-hosted
    steps:
      - name: check dependancies
        run: |
          python3 --version
          ls -lrt
    # - uses: actions/checkout@v3
    # - name: Setup Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.10'
    # - name: Install build dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install build
    #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # - name: Build package
    #   run: python -m build --sdist --wheel ./