# This is a basic workflow to help you get started with Actions

name: GitHub workflow on custom runners

# Controls when the workflow will run
on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "init"
  init:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout on code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: check files present in the directory
        run: ls -la

      - name: printing hostname
        run: echo $HOSTNAME
      - run: echo 'hello cloud gurus'
